

message:

  # Cool prefix
  prefix: "&6Emu &7>>"

  # Message sent when a player fails a check
  # Prefixes:
  # {prefix} - prefix from above value
  # {player} - player's name that failed
  # {check} - check name the player failed
  # {level} - new check level
  # {max} - maximum check level
  # {info} - reason why the player failed
  # {type} - the check type
  fail: "{prefix} &6{player} &7failed &6{check} ({type}) &7{level}/{max} &8{info}"

checks:

  # Combat

  killaura:
    a: # Attacked while dead
      enabled: true
      punishable: true
      max-level: 1

  velocity:
    a: # Vertical velocity
      enabled: true
      punishable: true
      max-level: 20

  # Move

  climb:
    a: # Speed on ladder
      enabled: true
      punishable: true
      max-level: 20
    b: # Height on ladder
      enabled: true
      punishable: true
      max-level: 20

  fly:
    a: # Prediction in air
      enabled: true
      punishable: true
      max-level: 20
    b: # Sudden motion reduction
      enabled: true
      punishable: true
      max-level: 20

  jesus:
    a: # Speed in liquid
      enabled: true
      punishable: true
      max-level: 20

  jump:
    a: # Max jump height
      enabled: true
      punishable: true
      max-level: 20

  noslow:
    a: # Speed in web
      enabled: true
      punishable: true
      max-level: 20

  speed:
    a: # Prediction in air
      enabled: true
      punishable: true
      max-level: 20
    b: # Max speed on ground
      enabled: true
      punishable: true
      max-level: 20
    c: # Max speed one tick after jumping
      enabled: true
      punishable: true
      max-level: 20
    d: # Max speed
      enabled: true
      punishable: true
      max-level: 20

  step:
    a: # Full block step
      enabled: true
      punishable: true
      max-level: 20
    b: # Reverse / Fast fall
      enabled: true
      punishable: true
      max-level: 20

  strafe:
    a: # Basic strafe
      enabled: true
      punishable: true
      max-level: 20

  # Packet

  badpackets:
    a: # Impossible pitch
      enabled: true
      punishable: true
      max-level: 20

  timer:
    a: # Balance
      enabled: true
      punishable: true
      max-level: 20
    b: # Average
      enabled: true
      punishable: true
      max-level: 20

  # Player

  ground:
    a: # Ground spoof
      enabled: true
      punishable: true
      max-level: 20
