

message:

  # Cool prefix
  prefix: "&7[&6Emu&7]"

  # Message sent when a player fails a check
  # Prefixes:
  # {prefix} - prefix from first value
  # {player} - player's name that failed
  # {check} - check name the player failed
  # {level} - new check level
  # {max} - maximum check level
  # {info} - reason why the player failed
  # {type} - the check type
  # {values} - details about the fail (what tick, difference in delta, etc.)
  fail: "{prefix} &6{player} &7failed &6{check} ({type}) &7x{level}"

  # Warning sent when a player gets teleported by the ghost block processor
  # Prefixes:
  # {prefix} - prefix from first value
  # {player} - player's name that was teleported
  gbp: "{prefix} &7[&6Warning&7] &6{player} &7was on a ghost block"

checks:

  velocity:
    a: # Vertical velocity
      enabled: true
      punishable: true
      max-level: 20
      min-buffer: 0

    b: # Horizontal velocity
      enabled: true
      punishable: true
      max-level: 20
      min-buffer: 0


  climb:
    a: # Speed on ladder
      enabled: true
      punishable: true
      max-level: 5
      min-buffer: 0

    b: # Height on ladder
      enabled: true
      punishable: true
      max-level: 15
      min-buffer: 0

  fly:
    a: # Prediction in air
      enabled: true
      punishable: true
      max-level: 20
      min-buffer: 0

    b: # Sudden motion reduction
      enabled: true
      punishable: true
      max-level: 5
      min-buffer: 0

  jesus:
    a: # Horizontal movement in liquid
      enabled: true
      punishable: true
      max-level: 15
      min-buffer: 0

    b: # Vertical movement in liquid
      enabled: true
      punishable: true
      max-level: 20
      min-buffer: 0

  jump:
    a: # Max jump height
      enabled: true
      punishable: true
      max-level: 20
      min-buffer: 0
    b: # Max speed on jump
      enabled: true
      punishable: true
      max-level: 20
      min-buffer: 0

  noslow:
    a: # Speed in web
      enabled: true
      punishable: true
      max-level: 5
      min-buffer: 0

  speed:
    a: # Prediction in air
      enabled: true
      punishable: true
      max-level: 20
      min-buffer: 0

    b: # Max speed on ground
      enabled: true
      punishable: true
      max-level: 30
      min-buffer: 0

    c: # Max speed one tick after jumping
      enabled: true
      punishable: true
      max-level: 3
      min-buffer: 0

    d: # Max speed
      enabled: true
      punishable: true
      max-level: 3
      min-buffer: 0

  move:
    a: # Invalid jump (ground speed detection)
      enabled: true
      punishable: true
      max-level: 20
      min-buffer: 0

  step:
    a: # Full block step
      enabled: true
      punishable: true
      max-level: 5
      min-buffer: 0

    b: # Reverse / Fast fall
      enabled: true
      punishable: true
      max-level: 3
      min-buffer: 0

    c: # Multi packet step
      enabled: true
      punishable: true
      max-level: 3
      min-buffer: 0

  strafe:
    a: # Prediction strafe
      enabled: true
      punishable: true
      max-level: 20
      min-buffer: 0

  badpackets:
    a: # Impossible pitch
      enabled: true
      punishable: true
      max-level: 1
      min-buffer: 0

    b: # Place Dig on same tick
      enabled: true
      punishable: true
      max-level: 1
      min-buffer: 0

    c: # Quick slot switching
      enabled: true
      punishable: true
      max-level: 1
      min-buffer: 0

  timer:
    a: # 50s
      enabled: true
      punishable: true
      max-level: 25
      min-buffer: 0

    b: # 50s
      enabled: true
      punishable: true
      max-level: 25
      min-buffer: 0

    c: # Average
      enabled: true
      punishable: true
      max-level: 25
      min-buffer: 0

  ground:
    a: # Ground spoof
      enabled: true
      punishable: true
      max-level: 5
      min-buffer: 0
