

message:

  # Cool prefix
  prefix: "&7[&6Emu&7]"

  # Message sent when a player fails a check
  # Prefixes:
  # {prefix} - prefix from first value
  # {player} - player's name that failed
  # {check} - check name the player failed
  # {level} - new check level
  # {max} - maximum check level
  # {info} - reason why the player failed
  # {type} - the check type
  # {values} - details about the fail (what tick, difference in delta, etc.)
  # {display} - "check.display" value
  fail: "{prefix} &6{player} &7failed &6{check} ({type}) &7x{level}"

  # Warning sent when a player gets teleported by the ghost block processor
  # Prefixes:
  # {prefix} - prefix from first value
  # {player} - player's name that was teleported
  gbp: "{prefix} &7[&6Warning&7] &6{player} &7was on a ghost block"

  # Message sent when a player sends an invalid sub command
  # Prefixes:
  # {prefix} - prefix from first value
  # {player} - player's name that was teleported
  invalid-command: "{prefix} &cInvalid command!"

# Check Guide -------------------
check-name:
  display: "Check Name" # What should the display name of the check be?
  enabled: true # Should this check be used?
  punishment: "ban" # How will this check punish the player? (kick, ban, none)
  max-level: 5 # How many levels until punishing the player?

  buffer:
    flag: 2 # How many times can the player flag without alerting staff?
    decay: 0.025 # How fast should the buffer decay when not flagging?
# -------------------------

punishments:
  kick: "/kick {player}"
  ban: "/msg {player} get detected!!"

checks:
  climb:
    a: # Horizontal movement on ladders
      display: "Climb"
      enabled: true
      punishment: "ban"
      max-level: 5

      buffer:
        flag: 2
        decay: 0.025

    b: # Vertical movement on ladders
      display: "Climb"
      enabled: true
      punishment: "ban"
      max-level: 5

      buffer:
        flag: 2
        decay: 0.02

  fly:
    a: # Vertical movement prediction in air
      display: "Fly"
      enabled: true
      punishment: "ban"
      max-level: 15

      buffer:
        flag: 2
        decay: 0.01

    b: # Sudden motion reduction
      display: "Fly"
      enabled: true
      punishment: "ban"
      max-level: 15

      buffer:
        flag: 2
        decay: 0.01

  ground:
    a: # Ground spoof
      display: "Ground"
      enabled: true
      punishment: "ban"
      max-level: 5

      buffer:
        flag: 2
        decay: 0.025

  hitbox:
    a: # Missed hitbox
      display: "Hitbox"
      enabled: true
      punishment: "ban"
      max-level: 5

      buffer:
        flag: 2
        decay: 0.01

  jesus:
    a: # Horizontal movement in liquid
      display: "Jesus"
      enabled: true
      punishment: "ban"
      max-level: 10

      buffer:
        flag: 2
        decay: 0.05

    b: # Vertical movement in liquid
      display: "Jesus"
      enabled: true
      punishment: "ban"
      max-level: 15

      buffer:
        flag: 2
        decay: 0.02

  jump:
    a: # Vertical movement after jumping
      display: "Jump"
      enabled: true
      punishment: "ban"
      max-level: 5

      buffer:
        flag: 0
        decay: 100

    b: # Horizontal movement after jumping
      display: "Jump"
      enabled: true
      punishment: "ban"
      max-level: 15

      buffer:
        flag: 1
        decay: 0.01

  killaura:
    a: # Multi Killaura
      display: "Killaura"
      enabled: true
      punishment: "kick"
      max-level: 5

      buffer:
        flag: 2
        decay: 0.2

  move:
    a: # Negative delta Y jump
      display: "Move"
      enabled: true
      punishment: "ban"
      max-level: 5

      buffer:
        flag: 7
        decay: 0.1

    b: # Impossible movement speed
      display: "Move"
      enabled: true
      punishment: "ban"
      max-level: 1

      buffer:
        flag: 0
        decay: 100

  noslow:
    a: # Horizontal movement in web
      display: "No Slow"
      enabled: true
      punishment: "ban"
      max-level: 5

      buffer:
        flag: 1
        decay: 0.05

  protocol:
    a: # Impossible pitch
      display: "Protocol"
      enabled: true
      punishment: "ban"
      max-level: 1

      buffer:
        flag: 0
        decay: 100

    b: # Placed and dug on same tick
      display: "Protocol"
      enabled: true
      punishment: "ban"
      max-level: 3

      buffer:
        flag: 2
        decay: 0.25

    c: # Switching slots too quickly
      display: "Protocol"
      enabled: true
      punishment: "ban"
      max-level: 3

      buffer:
        flag: 2
        decay: 0.25

    d: # Invalid held item change
      display: "Protocol"
      enabled: true
      punishment: "ban"
      max-level: 1

      buffer:
        flag: 0
        decay: 100

    e: # Started and stopped sprint on same tick
      display: "Protocol"
      enabled: true
      punishment: "ban"
      max-level: 3

      buffer:
        flag: 2
        decay: 0.15

    f: # Self-interact
      display: "Protocol"
      enabled: true
      punishment: "ban"
      max-level: 3

      buffer:
        flag: 0
        decay: 100

    g: # Bad sprint
      display: "Protocol"
      enabled: true
      punishment: "ban"
      max-level: 3

      buffer:
        flag: 0
        decay: 100

    h: # No Swing
      display: "Protocol"
      enabled: true
      punishment: "ban"
      max-level: 3

      buffer:
        flag: 0
        decay: 100

    i: # Invalid Digging
      display: "Protocol"
      enabled: true
      punishment: "ban"
      max-level: 3

      buffer:
        flag: 0
        decay: 100

  speed:
    a: # Horizontal movement prediction in air
      display: "Speed"
      enabled: true
      punishment: "ban"
      max-level: 10

      buffer:
        flag: 1
        decay: 0.02

    b: # Horizontal movement on ground
      display: "Speed"
      enabled: true
      punishment: "ban"
      max-level: 10

      buffer:
        flag: 3
        decay: 0.1

    c: # Horizontal speed after jumping
      display: "Speed"
      enabled: true
      punishment: "ban"
      max-level: 3

      buffer:
        flag: 2
        decay: 0.1

  step:
    a: # Invalid step height
      display: "Step"
      enabled: true
      punishment: "ban"
      max-level: 10

      buffer:
        flag: 0
        decay: 100

    b: # Fast fall
      display: "Step"
      enabled: true
      punishment: "ban"
      max-level: 10

      buffer:
        flag: 0
        decay: 100

    c: # Multi packet step
      display: "Step"
      enabled: true
      punishment: "ban"
      max-level: 3

      buffer:
        flag: 0
        decay: 100

  strafe:
    a: # Strafe in air / XZ prediction
      display: "Strafe"
      enabled: true
      punishment: "ban"
      max-level: 10

      buffer:
        flag: 5
        decay: 0.025

  timer:
    a: # Increased game speed
      display: "Timer"
      enabled: true
      punishment: "ban"
      max-level: 20

      buffer:
        flag: 12
        decay: 0.05

  velocity:
    a: # Vertical movement on velocity
      display: "Velocity"
      enabled: true
      punishment: "ban"
      max-level: 10

      buffer:
        flag: 1
        decay: 0.1

    b: # Horizontal movement on velocity
      display: "Velocity"
      enabled: true
      punishment: "ban"
      max-level: 15

      buffer:
        flag: 1
        decay: 0.1




