name: EmuAC
version: b2
description: Finally an anti-cheat made by an aussie
main: ac.emu.plugin.EmuPlugin

commands:
  emu:
    aliases: "ac"
    description: "Cool commands for emu"
    permission: "emu.command"

depend:
  - packetevents